
CC = clang++
FLAGS = -Wall -Wextra -Werror --std=c++98
NAME = main
CPPFILES = main.cpp \
			Sorcerer.cpp \
			Victim.cpp \
			Peon.cpp \
			BargeHaule.cpp

all:
	$(CC) $(FLAGS) -o $(NAME) $(CPPFILES)
	@./$(NAME)