
CC = clang++
FLAGS = -Wall -Wextra -Werror --std=c++98
NAME = main
CPPFILES = main.cpp \
			AssaultTerminator.cpp \
			Squad.cpp \
			TacticalMarine.cpp \

all:
	$(CC) $(FLAGS) -o $(NAME) $(CPPFILES)
	@./$(NAME)