
CC = clang++
FLAGS = -Wall -Wextra -Werror --std=c++98
NAME = main
CPPFILES = main.cpp \
			Bureaucrat.cpp \
			Form.cpp \
			PresidentialPardonForm.cpp  \
			RobotomyRequestForm.cpp \
			ShrubberyCreationForm.cpp

all:
	$(CC) $(FLAGS) -o $(NAME) $(CPPFILES)
	@./$(NAME)