#zombies makefile
CC = clang++
FLAGS = -Wall -Wextra -Werror
NAME = replace
SRCS =	main.cpp

all:
	$(CC) $(FLAGS) -o $(NAME) $(SRCS)
	@echo $(NAME) app created

fclean:
	@rm $(NAME)
	@echo $(NAME) app delete