apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx_im:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 443
        - containerPort: 80
        - containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  type: LoadBalancer

  selector:
    app: nginx
  ports:
    - port: 443
      name: port-https
      protocol: TCP
      targetPort: 443
    - port: 80
      name: port-http
      protocol: TCP
      targetPort: 80
    - port: 22
      name: port-ssh
      protocol: TCP
      targetPort: 22
