
CC = clang++
FLAGS = -Wall -Wextra -Werror --std=c++98
NAME = main
CPPFILES = main.cpp \
			AWeapon.cpp \
			Character.cpp \
			Enemy.cpp \
			PlasmaRifle.cpp \
			PowerFist.cpp \
			RadScorpion.cpp \
			SuperMutant.cpp

all:
	$(CC) $(FLAGS) -o $(NAME) $(CPPFILES)
	@./$(NAME)