#main.cpp makefile
CC = clang++
#FLAGS = -Wall -Wextra -Werror
NAME = main
SRCS =	main.cpp \
		Fixed.class.cpp

all:
	$(CC) $(FLAGS) -o $(NAME) $(SRCS)
	@echo $(NAME) app created

fclean:
	@rm $(NAME)
	@echo $(NAME) app delete
