
CC = clang++
FLAGS = -Wall -Wextra -Werror --std=c++98
NAME = main
CPPFILES = main.cpp \
			AMateria.cpp \
			Ice.cpp \
			Cure.cpp \
			Character.cpp \
			MateriaSource.cpp

all:
	$(CC) $(FLAGS) -o $(NAME) $(CPPFILES)
	@./$(NAME)