#func_rullet makefile
CC = clang++
FLAGS = -Wall -Wextra -Werror
NAME = func_rullet
SRCS =	main.cpp \
		Human.cpp

all:
	$(CC) $(FLAGS) -o $(NAME) $(SRCS)
	@echo $(NAME) app created

fclean:
	@rm $(NAME)
	@echo $(NAME) app delete